inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120
  IgnoredPatterns:
    - '\A#.+'
  Exclude:
    - "config/initializers/*"

Layout/MultilineMethodCallIndentation:
  Exclude:
    - "spec/**/*"

Lint/AmbiguousBlockAssociation:
  IgnoredMethods: [change]

Lint/EmptyBlock:
  Exclude:
    - "spec/models/**/*"

Metrics/AbcSize:
  Max: 30 # default 15

Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"
    - "spec/**/*"
    - "lib/tasks/auto_annotate_models.rake"
    - "config/environments/development.rb"

Metrics/ClassLength:
  Exclude:
    - "app/forms/product_form.rb"

Metrics/MethodLength:
  CountComments: false
  Max: 20

Naming/AccessorMethodName:
  Exclude:
    - "app/controllers/**/*"

Rails/HasManyOrHasOneDependent:
  Exclude:
    - "app/models/product_type.rb"
    - "app/models/social_service.rb"
    - "app/models/product_category.rb"

Style/AndOr:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma